services:
    db:
        image: mongo:latest
        container_name: database
        restart: unless-stopped
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
        ports:
            - "${DB_PORT}:27017"
        volumes:
            - carmedia-data:/data/db
        networks:
            - carmedia-network
networks:
    carmedia-network:
        driver: bridge

volumes:
    carmedia-data:
