version: "3"
services:
    db:
        image: arm7/mongo
        container_name: database
        restart: unless-stopped
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
        ports:
            - "${DB_PORT}:27017"
        volumes:
            - /opt/carmedia/db:/data/db
